### ISSUE TITLE
Renomear biblioteca.

### ISSUE THREAD

**Issue by ivmelo** [ivmelo/suap-api-php#16]
Pensei em renomear a biblioteca para suap-api-php, suap-php-api ou suapi-php. Thoughts?

@duartefq @JoabMendes @jeanjar

**Comment by JoabMendes** [comment]
suap-php-api :+1:

**Comment by jeanjar** [comment]
suapi-php

**Comment by ivmelo** [comment]
Renomeada para suap-api-php.

**Comment by duartefq** [comment]
php-ipa-paus
