### ISSUE TITLE
Atualizar documentação.

### ISSUE THREAD

**Issue by ivmelo** [ivmelo/suap-api-php#26]
Atualizar o README.MD com todos os novos métodos e funcionalidades do cliente.

**Comment by JoabMendes** [comment]
Man essas coisas de como usar é melhor vc por numa wiki aqui do repositório. Se não README.md fica muito longo. :wink:

**Comment by ivmelo** [comment]
Nah, povo não gosta de ler wiki.

Só colocar um sumário no readme e pá.

**Comment by JoabMendes** [comment]
ok

**Comment by ivmelo** [comment]
@JoabMendes se quiser escrever a wiki...
