### ISSUE TITLE
Filter courses by name.

### ISSUE THREAD

**Issue by ivmelo** [ivmelo/suap-api-php#8]
Ex. filterCourses('jogos processo') would return a list with Desenvolvimento de Jogos and Processo de Software.

**Comment by JoabMendes** [comment]
http://www.php.net/fnmatch

**Comment by duartefq** [comment]
Vish @JoabMendes, vc tava fazendo esse?

**Comment by JoabMendes** [comment]
@duartefq tava nao mas sugeri a biblioteca pra ajudar.

**Comment by JoabMendes** [comment]
@duartefq vi seu código. Não acha que um 
```
string strtolower ( string $str )
```
também seria interessante:

```php
 public function filterCoursesByName($ano_periodo = '', $course_names)
    {
        // Uses getGrades function as helper.
        $courses = $this->getGrades($ano_periodo);
        // removes trailing white spaces and sets regex
        $course_names = '/'.str_replace(' ', ' | ', strtolower(trim($course_names)) ).'/' //HERE
        $data = [];

        foreach ($courses as $course) {
            if ( preg_match($course_names, strtolower($course['disciplina'])) ){ //HERE
                array_push($data, $course)
            }
       }
        return $data;
   }
```

????

**Comment by JoabMendes** [comment]
@duartefq hello ?

**Comment by ivmelo** [comment]
@JoabMendes Ele fez, já tá no master.

**Comment by duartefq** [comment]
Acho que uma boa seria deixar esse método receber como parâmetro o course data, para depois usar o mesmo filtro em outras situações, como local de aula (passando como parametro um nome de curso), etc.

**Comment by ivmelo** [comment]
Algo do tipo ```search($string, $array);```?

**Comment by duartefq** [comment]
isso

**Comment by ivmelo** [comment]
feel free. ;)

só não esqueça os ;
